### ISSUE TITLE
0.8.0 cannot join error

### ISSUE THREAD

**Issue by Yurinann** [2lstudios-mc/FlameCord#101]
When player join:
```
[16:12:44 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@2668e837
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.util.Collection (java.util.LinkedHashMap and java.util.Collection are in module java.base of loader 'bootstrap')
        at net.md_5.bungee.conf.YamlConfig.getPermissions(YamlConfig.java:335) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at net.md_5.bungee.UserConnection.addGroups(UserConnection.java:565) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at net.md_5.bungee.UserConnection.init(UserConnection.java:170) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:678) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord-0.8.0.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:476b2f4:unknown]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

(Java 11.0.4)

**Comment by Yurinann** [comment]
Invalid
