### ISSUE TITLE
ViaVersion throws ClassNotFoundException

### ISSUE THREAD

**Issue by nhanledev** [2lstudios-mc/FlameCord#115]
Hello,

I encountered an error with ViaVersion throws some random stuff below:
This is a new build of FlameCord and latest ViaVersion 4.2.1.

```
[12:58:14 INFO]: Using mbed TLS based native cipher.
[12:58:14 INFO]: Using zlib based native compressor.
[12:58:14 INFO]: Enabled FlameCord version 0.8.4
[12:58:14 INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[12:58:14 INFO]: Epoll is working, utilising it!
[12:58:14 INFO]: Loaded plugin ViaVersion version 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[12:58:14 INFO] [ViaVersion]: Loading 1.12 -> 1.13 mappings...
[12:58:14 INFO] [ViaVersion]: Loading 1.13 -> 1.13.2 mappings...
[12:58:14 INFO] [ViaVersion]: Loading 1.13.2 -> 1.14 mappings...
[12:58:14 INFO] [ViaVersion]: Loading 1.14 -> 1.15 mappings...
[12:58:15 INFO] [ViaVersion]: Loading block connection mappings ...
[12:58:15 INFO] [ViaVersion]: Loading 1.15 -> 1.16 mappings...
[12:58:15 INFO] [ViaVersion]: Loading 1.16 -> 1.16.2 mappings...
[12:58:15 INFO] [ViaVersion]: Loading 1.16.2 -> 1.17 mappings...
[12:58:15 INFO] [ViaVersion]: Loading 1.17 -> 1.18 mappings...
[12:58:15 INFO]: Enabled plugin ViaVersion version 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[12:58:15 INFO] [ViaVersion]: ViaVersion detected lowest supported version by the proxy: 1.7-1.7.5 (4)
[12:58:15 INFO] [ViaVersion]: Highest supported version by the proxy: 1.18.2 (758)
[12:58:15 ERROR] [ViaVersion]: Error initializing BungeeServerHandler, try updating BungeeCord or ViaVersion!
[12:58:15 ERROR]: java.lang.ClassNotFoundException: net.md_5.bungee.entitymap.EntityMap
[12:58:15 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
[12:58:15 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[12:58:15 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:58:15 ERROR]:       at java.base/java.lang.Class.forName0(Native Method)
[12:58:15 ERROR]:       at java.base/java.lang.Class.forName(Class.java:375)
[12:58:15 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.<clinit>(BungeeServerHandler.java:71)
[12:58:15 ERROR]:       at com.viaversion.viaversion.bungee.platform.BungeeViaLoader.load(BungeeViaLoader.java:66)
[12:58:15 ERROR]:       at com.viaversion.viaversion.ViaManagerImpl.onServerLoaded(ViaManagerImpl.java:157)
[12:58:15 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[12:58:15 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:58:15 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:58:15 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[12:58:15 INFO]: Listening on /0.0.0.0:25565
[12:58:15 INFO] [ViaVersion]: Finished mapping loading, shutting down loader executor!
```

Step to reproduce:
1. Clone the FlameCord project and hit `./flamecord b`
2. Run FlameCord.jar
3. Install ViaVersion (latest til this date of issue is 4.2.1)
4. Run FlameCord.jar again

Why I report this on FlameCord: 
- Waterfall latest build 483 does not have this issue.

**Comment by nhanledev** [comment]
Saw ViaVersion not support at #109

**Comment by linsaftw** [comment]
> Saw ViaVersion not support at #109

Instead, run ViaVersion on all Spigot servers. This is the best solution. This has been done because of the high CPU usage.
