### ISSUE TITLE
Kicked with: server_went_down

### ISSUE THREAD

**Issue by andreasdc** [2lstudios-mc/FlameCord#118]
I'm often getting kicked after connecting to the server with server_went_down message, but there are no errors on spigot or bungee.

**Comment by andreasdc** [comment]
> > I'm often getting kicked after connecting to the server with server_went_down message, but there are no errors on spigot or bungee.
> 
> That's weird, but wait the pull-request is merged and try again.

This one? https://github.com/2lstudios-mc/FlameCord/pull/117

**Comment by xIsm4** [comment]
> > > I'm often getting kicked after connecting to the server with server_went_down message, but there are no errors on spigot or bungee.
> > 
> > 
> > That's weird, but wait the pull-request is merged and try again.
> 
> This one? #117

yep.

**Comment by andreasdc** [comment]
> > > > I'm often getting kicked after connecting to the server with server_went_down message, but there are no errors on spigot or bungee.
> > > 
> > > 
> > > That's weird, but wait the pull-request is merged and try again.
> > 
> > 
> > This one? #117
> 
> yep.

How will it help with my problem?

**Comment by xIsm4** [comment]
> > > > > I'm often getting kicked after connecting to the server with server_went_down message, but there are no errors on spigot or bungee.
> > > > 
> > > > 
> > > > That's weird, but wait the pull-request is merged and try again.
> > > 
> > > 
> > > This one? #117
> > 
> > 
> > yep.
> 
> How will it help with my problem?

I guess showing again that exception of Bungee, but im sure that some plugin or bad config is doing that for you.

**Comment by andreasdc** [comment]
> > > > > > I'm often getting kicked after connecting to the server with server_went_down message, but there are no errors on spigot or bungee.
> > > > > 
> > > > > 
> > > > > That's weird, but wait the pull-request is merged and try again.
> > > > 
> > > > 
> > > > This one? #117
> > > 
> > > 
> > > yep.
> > 
> > 
> > How will it help with my problem?
> 
> I guess showing again that exception of Bungee, but im sure that some plugin or bad config is doing that for you.

It happens when I switch the server, only thing that I see is 'disconnected' in logs and message from server_went_down.

**Comment by andreasdc** [comment]
There's nothing in proxy logs.

**Comment by linsaftw** [comment]
If the server went down that doesn't have to do with FlameCord but to the spigot server itself.

**Comment by andreasdc** [comment]
> If the server went down that doesn't have to do with FlameCord but to the spigot server itself.

The server didn't go down and spigot just shows 'disconnected'.

**Comment by linsaftw** [comment]
Can you test on a clean local server and see if the same issue happens? I think it is a plugin sending invalid packet or something similar. Enable all logger options on FlameCord to show extra info.

**Comment by andreasdc** [comment]
> Can you test on a clean local server and see if the same issue happens? I think it is a plugin sending invalid packet or something similar. Enable all logger options on FlameCord to show extra info.

It happens on particular servers, I will test with loggers enabled.

**Comment by andreasdc** [comment]
> Can you test on a clean local server and see if the same issue happens? I think it is a plugin sending invalid packet or something similar. Enable all logger options on FlameCord to show extra info.

I have the error:
java.lang.IllegalArgumentException: Objective sbUsername already exists in this scoreboard

**Comment by andreasdc** [comment]
Full error:
java.lang.IllegalArgumentException: Objective sbUsername already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:189) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:87) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:132) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by linsaftw** [comment]
This is because of the scoreboard plugin or Via similar plugins. Nothing we can do from our end.

**Comment by andreasdc** [comment]
> This is because of the scoreboard plugin or Via similar plugins. Nothing we can do from our end. Error comes from spigot itself.

https://github.com/PaperMC/Waterfall/issues/318

**Comment by linsaftw** [comment]
> > This is because of the scoreboard plugin or Via similar plugins. Nothing we can do from our end. Error comes from spigot itself.
> 
> [PaperMC/Waterfall#318](https://github.com/PaperMC/Waterfall/issues/318)

It depends on how the plugin handles scoreboards. Using a different plugin will fix. (From my experience)
