### ISSUE TITLE
class not found exception when enabling viaversion

### ISSUE THREAD

**Issue by madmobhunter** [2lstudios-mc/FlameCord#126]
I never had this issue with older releases of FlameCord. 

[11:56:35 INFO]: Enabled plugin ViaVersion version 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[11:56:35 INFO] [ViaVersion]: ViaVersion detected lowest supported version by the proxy: 1.7-1.7.5 (4)
[11:56:35 INFO] [ViaVersion]: Highest supported version by the proxy: 1.18.2 (758)
[11:56:35 ERROR] [ViaVersion]: Error initializing BungeeServerHandler, try updating BungeeCord or ViaVersion!
[11:56:35 ERROR]: java.lang.ClassNotFoundException: net.md_5.bungee.entitymap.EntityMap
[11:56:35 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
[11:56:35 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[11:56:35 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[11:56:35 ERROR]:       at java.base/java.lang.Class.forName0(Native Method)
[11:56:35 ERROR]:       at java.base/java.lang.Class.forName(Class.java:375)
[11:56:35 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.<clinit>(BungeeServerHandler.java:71)
[11:56:35 ERROR]:       at com.viaversion.viaversion.bungee.platform.BungeeViaLoader.load(BungeeViaLoader.java:66)
[11:56:35 ERROR]:       at com.viaversion.viaversion.ViaManagerImpl.onServerLoaded(ViaManagerImpl.java:157)
[11:56:35 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[11:56:35 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:56:35 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:56:35 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[11:56:35 INFO]: Listening on /0.0.0.0:25565
[11:56:35 INFO] [ViaVersion]: Finished mapping loading, shutting down loader executor!

**Comment by linsaftw** [comment]
ViaVersion was intentionally disabled on BungeeCord to prevent performance issues.

As stated on https://www.mc-market.org/resources/13492/

"For performance measures, reducing CPU usage by 50%, ViaVersion is disabled from running on FlameCord.

HOWEVER, you can run ViaVersion on all your backend Spigot servers and it will have the same effect without the performance degradation of having it on FlameCord."
