### ISSUE TITLE
io.netty.util.IllegalReferenceCountException error when trying to join

### ISSUE THREAD

**Issue by Gyztor** [2lstudios-mc/FlameCord#144]
When attempting to join a server with 1.19 that uses viaversion and is a native 1.18.2 server (and possibly other native server versions could be plagued by this) there is this error that appears every time you join:
```
[lobby] Exception caught: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
```
i have attempting to figure out what the issue is and someone else has noticed this issue too:
![image](https://user-images.githubusercontent.com/44737827/177030948-5770f0c6-4458-4eb9-a645-8daea94cedb0.png)
and for some reason this is only a flamecord issue as Bungee and Waterfall seem to be doing fine (and even updating to the latest upstreams does not seem to matter as i always build flamecord to the latest commits of flamecord, waterfall and bungeecord). For servers that use something like Reconnect they get stuck in a loading loop unable to leave unless they FULLY close Minecraft or get lucky enough to get past "loading terrain" i thought this was a viaversion issue but with testing with building all the different ones etc etc i have not seem much of a difference between 4.3.0-[4.3.2SNAPSHOT](https://ci.viaversion.com/job/ViaVersion/) (build 621 as of writing and testing). the only noticed behavior on the player side is they do manage to at least get to the back-end paper servers but do get kicked by the flamecord but treats it like a kick from the back-end server (not the back-end server when checking logs as the back-end paper servers only show "disconnected" and nothing else).

**Comment by Gyztor** [comment]
> Looks like flamecord needs to pull the latest waterfall to see if this still persists

it still persists with latest waterfall from building it myself. maybe you could try building it and see if there are different results somehow? though i doubt there would be.

**Comment by xIsm4** [comment]
> When attempting to join a server with 1.19 that uses viaversion and is a native 1.18.2 server (and possibly other native server versions could be plagued by this) there is this error that appears every time you join:
> 
> ```
> [lobby] Exception caught: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
> ```
> 
> i have attempting to figure out what the issue is and someone else has noticed this issue too: ![image](https://user-images.githubusercontent.com/44737827/177030948-5770f0c6-4458-4eb9-a645-8daea94cedb0.png) and for some reason this is only a flamecord issue as Bungee and Waterfall seem to be doing fine (and even updating to the latest upstreams does not seem to matter as i always build flamecord to the latest commits of flamecord, waterfall and bungeecord). For servers that use something like Reconnect they get stuck in a loading loop unable to leave unless they FULLY close Minecraft or get lucky enough to get past "loading terrain" i thought this was a viaversion issue but with testing with building all the different ones etc etc i have not seem much of a difference between 4.3.0-[4.3.2SNAPSHOT](https://ci.viaversion.com/job/ViaVersion/) (build 621 as of writing and testing). the only noticed behavior on the player side is they do manage to at least get to the back-end paper servers but do get kicked by the flamecord but treats it like a kick from the back-end server (not the back-end server when checking logs as the back-end paper servers only show "disconnected" and nothing else).

It could be the system to avoid copy buf packets, if you want help add me on discord and ill try to fix it for you:
xIsm4#9127

**Comment by Gyztor** [comment]
> > When attempting to join a server with 1.19 that uses viaversion and is a native 1.18.2 server (and possibly other native server versions could be plagued by this) there is this error that appears every time you join:
> > ```
> > [lobby] Exception caught: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i have attempting to figure out what the issue is and someone else has noticed this issue too: ![image](https://user-images.githubusercontent.com/44737827/177030948-5770f0c6-4458-4eb9-a645-8daea94cedb0.png) and for some reason this is only a flamecord issue as Bungee and Waterfall seem to be doing fine (and even updating to the latest upstreams does not seem to matter as i always build flamecord to the latest commits of flamecord, waterfall and bungeecord). For servers that use something like Reconnect they get stuck in a loading loop unable to leave unless they FULLY close Minecraft or get lucky enough to get past "loading terrain" i thought this was a viaversion issue but with testing with building all the different ones etc etc i have not seem much of a difference between 4.3.0-[4.3.2SNAPSHOT](https://ci.viaversion.com/job/ViaVersion/) (build 621 as of writing and testing). the only noticed behavior on the player side is they do manage to at least get to the back-end paper servers but do get kicked by the flamecord but treats it like a kick from the back-end server (not the back-end server when checking logs as the back-end paper servers only show "disconnected" and nothing else).
> 
> It could be the system to avoid copy buf packets, if you want help add me on discord and ill try to fix it for you: xIsm4#9127

i was going to do some tests that involve testing a server with flamecord and a 1.19 paper server but i havent gotten around to doing that, but if i dont notice anything different with a test 1.19 paper server and this still appears on 1.19 trying to join than i will definately let you know asap and see if we can fix this, Though if we do get it fixed through discord (when/if that time comes) do you mind if we posted the results and testing we did here to make sure people can also apply any fixes we find?

**Comment by linsaftw** [comment]
Something might have changed on 1.19 that makes the packets not able to properly read with our split method. You using ViaVersion on Spigot servers and not on Bungee right? (Bungee ViaVersion is not supported, instead use it on all individual servers)

**Comment by kamilleon** [comment]
Originally I wrote that discord message, and yes, I use ViaVersion only on the spigot servers, and also something that I managed to find out:

- While running FlameCord this issue only happens if the Spigot server versions are 1.8-1.18.2 (about 1.7, idk.), on 1.19 this does not happen anymore.
- Also without using ViaVersion this still happens on the versions I listed.

**Comment by linsaftw** [comment]
Thats so weird! We need to figure out why it started happening suddenly like this.

**Comment by Gyztor** [comment]
I personally build the plugin with latest waterfall and bungee from their respective master branches as i do with flamecord. But i think it started since 1.19 support was added fully. So flamecord 1.0.0 i think

**Comment by linsaftw** [comment]
I have updated upstream of FlameCord and it seems to work fine with ViaVersion + 1.16.5 purpur

**Comment by Gyztor** [comment]
Error persists still. maybe to try and eliminate all variables try using 1.18.2 paper with viaversion 4.3.1 and viabackwards 4.3.1 on the paper server. than have flamecord run like normal and see if anything changes, its possible its a paper specific thing and somehow purpur magically gets around it

**Comment by linsaftw** [comment]
Can't reproduce this error. Running FlameCord 1.0.4 and ViaVersion (Latest from Spigot).

**Comment by kamilleon** [comment]
My issue still persists on Paper and normal Spigot 1.8.8, on other newer versions (1.17+) seems fixed.

Steps to reproduce:
- Download [CombatLogX](https://www.spigotmc.org/resources/combatlogx.31689/), [SirblobmanCore](https://www.spigotmc.org/resources/sirblobmancore.83189/) and [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/).
- Add [WorldGuard](https://dev.curseforge.com/projects/worldguard/files/956770) and [WorldEdit](https://dev.bukkit.org/projects/worldedit/files/922048) to plugins folder.
- Add WorldGuard Compatibility to the expansions folder and enable force-field.
- Start 1.8.8 Spigot server and FlameCord.
- Make a PVP allowed, and PVP denied area with WorldGuard.
- Have 2 accounts online, and hit one of the accounts with the other one.
- Try to break the combat wall with one of the accounts -> gets kicked.

**Comment by linsaftw** [comment]
That is not an issue with FlameCord then.

**Comment by kamilleon** [comment]
This does not happen on latest Waterfall, but on FlameCord it does

Waterfall:
https://user-images.githubusercontent.com/25117301/178341637-d941e35a-4afc-4cd5-9d58-e2abe9197b0d.mp4

FlameCord:
https://user-images.githubusercontent.com/25117301/178341652-500d0dfd-3a6f-45d9-aaa7-451800a04069.mp4

**Comment by Gyztor** [comment]
alright i managed to crash flamecord with the error to get a stacktrace
```
[16:10:31 WARN]: [/[lol not getting this local ip]:46334|GyztorMizirath] <-> DownstreamBridge <-> [lobby] - A decoder exception has been thrown:
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90) ~[flamecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:27ca438:unknown]
        ... 24 more
[16:10:31 INFO]: [GyztorMizirath] disconnected with: The server you were previously on went down, you have been connected to a fallback server
```

**Comment by linsaftw** [comment]
I wasn't able to reproduce this error. If any plugin has incompatibilities with FlameCord's removal of copy() function then the author has to fix the compatibility himself because removing this will make FlameCord extremely vulnerable to attacks.

I understand the problem, but FlameCord won't follow bad practices because a couple of developers won't update their plugins. This is the same reason why we don't support ViaVersion installed on BungeeCord.

Removing this would be similar to using Waterfall with 2LS AntiBot.

**Comment by Gyztor** [comment]
but none of my plugins have EVERY broken before UNTIL your 1.0.0 update and the error shows that it isn't a plugin so i don't understand what you mean, I have even tested this without any plugins on flamecord and this still occurs anyways

**Comment by Gyztor** [comment]
Issue still persists as of 1.0.5 but it does get further than before and at least gets past the loading world part though you are kinda just spawned in a black void, but it's progress

**Comment by linsaftw** [comment]
> but none of my plugins have EVER broken before UNTIL your 1.0.0 update and the error shows that it isn't a plugin so i don't understand what you mean, I have even tested this without any plugins on flamecord and this still occurs anyways

So the error is since Waterfall update right?

**Comment by Gyztor** [comment]
> So the error is since Waterfall update right? Does it happen with Waterfall?

Sorry for a late response, irl stuff has been hectic. The error has been since waterfall's update but waterfall has since resolved it on their side (either by luck, accident or intentionally i can't figure out which commit changed it) but it still appears on flamecord which most likely means its some kind of conflict, but i have also seen you have updated flamecord to 1.0.6 so let me try that version rq and see if anything has changed at all.

**Comment by Gyztor** [comment]
Good news seems to have fixed itself for me!
