### ISSUE TITLE
The return of Exception caught: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

### ISSUE THREAD

**Issue by Gyztor** [2lstudios-mc/FlameCord#155]
Previous issue: https://github.com/2lstudios-mc/FlameCord/issues/144
So around august 1st my issue seemed to have magically resolved but after building 1.0.9 with the latest bungee and waterfall upstream the error has returned! (sadly) I am unsure why, but it's back now.
```
[14:22:48 INFO]: [GyztorMizirath|/{ANIPHERE}:52384] <-> ServerConnector [lobby] has connected
[14:22:48 WARN]: [/{ANIPHERE}:52384|GyztorMizirath] <-> DownstreamBridge <-> [lobby] - A decoder exception has been thrown:
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:78552cd:unknown]
        ... 24 more
[14:22:48 INFO]: [GyztorMizirath] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[14:22:48 INFO]: [/{ANIPHERE}:52384|GyztorMizirath] -> UpstreamBridge has disconnected
[14:22:48 INFO]: [/{ANIPHERE}:52384|GyztorMizirath] <-> DownstreamBridge <-> [lobby] has disconnected
```

**Comment by Gyztor** [comment]
Good news though, there is a slight difference in behavior than before. I have made a testing 1.19 server and switching to that server when trying to join on a 1.19.x client will actually not kick me (using something like bungee-reconnect (https://www.spigotmc.org/resources/automatic-server-reconnect-bungee-reconnect.84395/) to ensure i don't get kicked completely)

**Comment by andreasdc** [comment]
Do you use ProtocolLib?

**Comment by Gyztor** [comment]
yes? but i don't exactly see how that would do anything as protocol lib doesn't work on proxies

**Comment by andreasdc** [comment]
I saw similar error when I installed Plib, check without it.

**Comment by linsaftw** [comment]
I don't think this has anything to do with FlameCord but with the plugins installed in the backend. (yes, they are relevant in this kind of issues)

**Comment by Gyztor** [comment]
> I don't think this has anything to do with FlameCord but with the plugins installed in the backend. (yes, they are relevant in this kind of issues)

also can i please ask for this to be reopened at least until its resolved (i will close it when it is and will post what happened and any links to places that i need to)

> I saw similar error when I installed Plib, check without it.

I will give this a shot and see what happens but i should mention there is **NO ERRORS** in the backend servers

**Comment by Gyztor** [comment]
I have now tested with a fresh install backend server. issue persists

**Comment by andreasdc** [comment]
What backend server version?

**Comment by Gyztor** [comment]
paper 1.18.2 latest build of that. i also have the latest paper 1.19.2 build as a server attached the same bungeecord. that one works fine its only the 1.18.2

**Comment by Gyztor** [comment]
when using a 1.19.x client.

**Comment by Gyztor** [comment]
Okay i think i found out something. on the clean server install i have found that now this error appears when taking fall damage and i get disconnected with no error to the backend but one in the flamecord

**Comment by Gyztor** [comment]
This seems to also exist in waterfall

**Comment by linsaftw** [comment]
I see it's not related to FlameCord then. Maybe try a clean install.
