### ISSUE TITLE
Error with password checker

### ISSUE THREAD

**Issue by Souipi** [2lstudios-mc/FlameCord#180]
I am instantly kicked after I typing my password.

The error in my console :

```
[21:32:17 ERROR]: [***|Souipi] -> UpstreamBridge - encountered exception
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "nickname" is null
        at dev._2lstudios.flamecord.antibot.PasswordCheck.updatePassword(PasswordCheck.java:21) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at dev._2lstudios.flamecord.antibot.PasswordCheck.check(PasswordCheck.java:44) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:223) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:171) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:73) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:131) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord-1.2.3.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:2ff4886:unknown]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by linsaftw** [comment]
Fixed. Soon released.
